name: Build and Test (SBT)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.BUILD_TOKEN }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run: |
          printf "realm=github\nhost=www.github.com\nuser=${{ secrets.BUILD_USERNAME }}\password=${{ secrets.BUILD_TOKEN }}" > ~/gihub.credentials
          printf "[github]\n  actor=${{ secrets.BUILD_USERNAME }}\n  token=${{ secrets.BUILD_TOKEN }}" > ~/.gitconfig
          sbt backend/test trayUtil/test backend/products
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_USERNAME: ${{ secrets.BUILD_USERNAME }}
          BUILD_TOKEN: ${{ secrets.BUILD_TOKEN }}
