name: Deploy Docker to GCloud

on:
  push:
    branches:
      - master
      - docker

jobs:
  deploy:
    name: Deploy using GCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.ORG_TOKEN }}
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Prepare environment secrets
        run: |
          printf "${{ secrets.GCP_SA_KEY }}" > backend/src/main/resources/sa.json

      - name: Assembly
        run: |
          printf "realm=github\nhost=www.github.com\nuser=${{ secrets.ORG_USERNAME }}\password=${{ secrets.ORG_TOKEN }}" > ~/gihub.credentials
          printf "[github]\n  actor=${{ secrets.ORG_USERNAME }}\n  token=${{ secrets.ORG_TOKEN }}" > ~/.gitconfig
          sbt backend/Docker/publishLocal
      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Deploy to GCloud
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev
          docker tag loctio:0.4.2-beta europe-west1-docker.pkg.dev/loctio/loctio/loctio:v0.4.2-beta
          docker push europe-west1-docker.pkg.dev/loctio/loctio/loctio:v0.4.2-beta
